import type { Graph, AnalysisResult } from '@repo-xray/core';
import { basename } from 'node:path';

export function generateAgents(graph: Graph, analysis: AnalysisResult): string {
  const name = basename(graph.rootDir);
  const lines: string[] = [];

  lines.push(`# ${name}`);
  lines.push('');
  lines.push('<!-- Auto-generated by repo-xray — do not edit manually. -->');
  lines.push('');

  // Codebase Overview
  lines.push('## Codebase Overview');
  lines.push('');
  lines.push(`- **Language:** ${graph.meta.language}`);
  lines.push(`- **Module count:** ${graph.meta.totalModules}`);
  lines.push(`- **Total symbols:** ${graph.meta.totalSymbols}`);
  if (analysis.entryPoints.length > 0) {
    lines.push(`- **Entry points:** ${analysis.entryPoints.join(', ')}`);
  }
  lines.push('');

  // Module Map
  lines.push('## Module Map');
  lines.push('');
  const layerOrder = ['entry', 'core', 'util', 'type', 'config', 'test'];
  const allLayers = Object.keys(analysis.layers);
  const orderedLayers = [
    ...layerOrder.filter(l => allLayers.includes(l)),
    ...allLayers.filter(l => !layerOrder.includes(l)),
  ];
  for (const layer of orderedLayers) {
    const modules = analysis.layers[layer];
    if (!modules || modules.length === 0) continue;
    lines.push(`### ${layer}`);
    lines.push('');
    for (const mod of modules) {
      const node = graph.nodes.get(mod);
      const exports = node
        ? node.symbols.filter(s => s.exported).map(s => s.name).join(', ')
        : '';
      lines.push(`- \`${mod}\`${exports ? ` — exports: ${exports}` : ''}`);
    }
    lines.push('');
  }

  // Conventions
  lines.push('## Conventions');
  lines.push('');
  const c = analysis.conventions;
  lines.push(`- Export style: ${c.exportStyle}`);
  lines.push(`- Function naming: ${c.namingFunctions}`);
  lines.push(`- Class naming: ${c.namingClasses}`);
  lines.push(`- File structure: ${c.fileStructure}`);
  lines.push(`- Test pattern: ${c.testPattern}`);
  lines.push('');

  // Warnings
  if (analysis.circularDeps.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    lines.push('### Circular Dependencies');
    lines.push('');
    for (const [a, b] of analysis.circularDeps) {
      lines.push(`- \`${a}\` ↔ \`${b}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}
