import type { Graph, AnalysisResult } from '@repo-xray/core';
import { basename, join, dirname } from 'node:path';
import { readFileSync } from 'node:fs';

interface PkgInfo {
  name: string;
  description?: string;
  dependencies: string[];
}

function readPkgInfo(rootDir: string): PkgInfo {
  const fallback: PkgInfo = { name: basename(rootDir), dependencies: [] };
  try {
    const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
    return {
      name: pkg.name || fallback.name,
      description: pkg.description,
      dependencies: [
        ...Object.keys(pkg.dependencies ?? {}),
        ...Object.keys(pkg.devDependencies ?? {}),
      ],
    };
  } catch {
    return fallback;
  }
}

function detectStack(deps: string[]): string[] {
  const stack: string[] = [];
  const checks: [string, string[]][] = [
    ['Next.js', ['next']],
    ['React', ['react']],
    ['Vue', ['vue']],
    ['Svelte', ['svelte']],
    ['Angular', ['@angular/core']],
    ['NestJS', ['@nestjs/core']],
    ['Express', ['express']],
    ['Fastify', ['fastify']],
    ['Prisma', ['prisma', '@prisma/client']],
    ['Drizzle', ['drizzle-orm']],
    ['TypeORM', ['typeorm']],
    ['Zustand', ['zustand']],
    ['Redux', ['@reduxjs/toolkit', 'redux']],
    ['MobX', ['mobx']],
    ['Tailwind CSS', ['tailwindcss']],
    ['Vite', ['vite']],
    ['Webpack', ['webpack']],
    ['Vitest', ['vitest']],
    ['Jest', ['jest']],
    ['Playwright', ['@playwright/test', 'playwright']],
    ['Dexie', ['dexie']],
    ['D3', ['d3', 'd3-force']],
  ];
  for (const [name, pkgs] of checks) {
    if (pkgs.some(p => deps.includes(p))) {
      stack.push(name);
    }
  }
  return stack;
}

function getDirSummary(graph: Graph): Map<string, number> {
  const dirs = new Map<string, number>();
  for (const id of graph.nodes.keys()) {
    const parts = id.split('/');
    // Get meaningful directory level: "src/components" not just "src"
    let dir: string;
    if (parts.length <= 1) {
      dir = '.';
    } else if (parts.length === 2) {
      dir = parts[0];
    } else {
      dir = parts.slice(0, 2).join('/');
    }
    dirs.set(dir, (dirs.get(dir) ?? 0) + 1);
  }
  return dirs;
}

function getDirDependencies(graph: Graph): string[] {
  // Directory-level dependency map (compact)
  const dirEdges = new Map<string, Map<string, number>>();

  for (const edge of graph.edges) {
    const fromDir = getDirKey(edge.from);
    const toDir = getDirKey(edge.to);
    if (fromDir === toDir) continue;

    if (!dirEdges.has(fromDir)) dirEdges.set(fromDir, new Map());
    const targets = dirEdges.get(fromDir)!;
    targets.set(toDir, (targets.get(toDir) ?? 0) + 1);
  }

  const lines: string[] = [];
  // Sort by number of outgoing connections
  const sorted = [...dirEdges.entries()].sort((a, b) => b[1].size - a[1].size);

  for (const [from, targets] of sorted) {
    const targetList = [...targets.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([dir, count]) => count > 1 ? `${dir} (${count})` : dir);
    lines.push(`- ${from} → ${targetList.join(', ')}`);
  }

  return lines;
}

function getDirKey(fileId: string): string {
  const parts = fileId.split('/');
  if (parts.length <= 1) return '.';
  if (parts.length === 2) return parts[0];
  return parts.slice(0, 2).join('/');
}

export function generateClaude(graph: Graph, analysis: AnalysisResult): string {
  const pkg = readPkgInfo(graph.rootDir);
  const stack = detectStack(pkg.dependencies);
  const dirSummary = getDirSummary(graph);
  const lines: string[] = [];

  lines.push(`# Project: ${pkg.name}`);
  lines.push('');
  lines.push('> Auto-generated by repo-xray — do not edit manually.');
  lines.push('');

  // Project description & stack
  if (pkg.description || stack.length > 0) {
    lines.push('## Overview');
    lines.push('');
    if (pkg.description) {
      lines.push(pkg.description);
      lines.push('');
    }
    if (stack.length > 0) {
      lines.push(`**Stack:** ${stack.join(', ')}`);
      lines.push('');
    }
  }

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  lines.push(`- **Language:** ${graph.meta.language}`);
  lines.push(`- **Modules:** ${graph.meta.totalModules}`);
  lines.push('');

  // Directory summary
  lines.push('**Directory structure:**');
  lines.push('');
  const sortedDirs = [...dirSummary.entries()].sort((a, b) => b[1] - a[1]);
  for (const [dir, count] of sortedDirs) {
    lines.push(`- \`${dir}/\` — ${count} files`);
  }
  lines.push('');

  // Entry points (only real ones)
  if (analysis.entryPoints.length > 0) {
    lines.push('**Entry points:**');
    lines.push('');
    for (const ep of analysis.entryPoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push('');
  }

  // Key Modules
  lines.push('## Key Modules');
  lines.push('');
  for (const mod of analysis.keyModules) {
    const node = graph.nodes.get(mod.id);
    const exports = node
      ? node.symbols.filter(s => s.exported).map(s => s.name).join(', ')
      : '';
    lines.push(`- **\`${mod.id}\`** — ${mod.reason} (in: ${mod.inDegree}, out: ${mod.outDegree})${exports ? '. Exports: ' + exports : ''}`);
  }
  lines.push('');

  // Directory-level dependency map (compact)
  const dirDeps = getDirDependencies(graph);
  if (dirDeps.length > 0) {
    lines.push('## Dependencies (directory level)');
    lines.push('');
    for (const line of dirDeps) {
      lines.push(line);
    }
    lines.push('');
  }

  // Conventions (skip unknown/mixed values)
  const c = analysis.conventions;
  const conventions: string[] = [];
  if (c.exportStyle !== 'mixed') conventions.push(`${c.exportStyle} exports`);
  if (c.namingFunctions !== 'mixed') conventions.push(`functions: ${c.namingFunctions}`);
  if (c.namingClasses !== 'unknown' && c.namingClasses !== 'mixed') conventions.push(`classes: ${c.namingClasses}`);
  if (c.testPattern !== 'none') conventions.push(`tests: ${c.testPattern}`);

  if (conventions.length > 0) {
    lines.push('## Conventions');
    lines.push('');
    lines.push(conventions.join(' · '));
    lines.push('');
  }

  // Circular Dependencies
  if (analysis.circularDeps.length > 0) {
    lines.push('## Circular Dependencies');
    lines.push('');
    for (const [a, b] of analysis.circularDeps) {
      lines.push(`- \`${a}\` ↔ \`${b}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}
