import type { Graph, AnalysisResult } from '@repo-xray/core';
import { basename } from 'node:path';

export function generateClaude(graph: Graph, analysis: AnalysisResult): string {
  const name = basename(graph.rootDir);
  const lines: string[] = [];

  lines.push(`# Project: ${name}`);
  lines.push('');
  lines.push('> Auto-generated by repo-xray — do not edit manually.');
  lines.push('');

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  if (analysis.entryPoints.length > 0) {
    lines.push(`- **Entry points:** ${analysis.entryPoints.join(', ')}`);
  }
  lines.push(`- **Module count:** ${graph.meta.totalModules}`);
  lines.push(`- **Language:** ${graph.meta.language}`);
  lines.push('');

  // Key Modules
  lines.push('## Key Modules');
  lines.push('');
  for (const mod of analysis.keyModules) {
    const node = graph.nodes.get(mod.id);
    const exports = node
      ? node.symbols.filter(s => s.exported).map(s => s.name).join(', ')
      : '';
    lines.push(`### \`${mod.id}\``);
    lines.push(`- **Reason:** ${mod.reason}`);
    lines.push(`- **In/Out degree:** ${mod.inDegree}/${mod.outDegree}`);
    if (exports) {
      lines.push(`- **Exports:** ${exports}`);
    }
    lines.push('');
  }

  // Dependency Map
  lines.push('## Dependency Map');
  lines.push('');
  const depMap = new Map<string, string[]>();
  for (const edge of graph.edges) {
    if (!depMap.has(edge.from)) depMap.set(edge.from, []);
    depMap.get(edge.from)!.push(edge.to);
  }
  for (const [from, tos] of depMap) {
    lines.push(`- \`${from}\` → ${tos.map(t => `\`${t}\``).join(', ')}`);
  }
  if (depMap.size === 0) {
    lines.push('No dependencies detected.');
  }
  lines.push('');

  // Conventions
  lines.push('## Conventions');
  lines.push('');
  const c = analysis.conventions;
  lines.push(`- **Export style:** ${c.exportStyle}`);
  lines.push(`- **Naming (functions):** ${c.namingFunctions}`);
  lines.push(`- **Naming (classes):** ${c.namingClasses}`);
  lines.push(`- **File structure:** ${c.fileStructure}`);
  lines.push(`- **Tests:** ${c.testPattern}`);
  lines.push('');

  // Circular Dependencies
  if (analysis.circularDeps.length > 0) {
    lines.push('## Circular Dependencies');
    lines.push('');
    for (const [a, b] of analysis.circularDeps) {
      lines.push(`- \`${a}\` ↔ \`${b}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}
