import type { Graph, AnalysisResult } from '@repo-xray/core';
import { basename, join } from 'node:path';
import { readFileSync } from 'node:fs';

function getProjectName(rootDir: string): string {
  try {
    const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
    if (pkg.name) return pkg.name;
  } catch {}
  return basename(rootDir);
}

export function generateCursor(graph: Graph, analysis: AnalysisResult): string {
  const name = getProjectName(graph.rootDir);
  const lines: string[] = [];

  lines.push('# Project Rules');
  lines.push('');
  lines.push(`# Auto-generated by repo-xray for ${name} — do not edit manually.`);
  lines.push('');

  // Project Structure
  lines.push('## Project Structure');
  lines.push('');
  lines.push(`- Language: ${graph.meta.language}`);
  lines.push(`- Modules: ${graph.meta.totalModules}`);
  if (analysis.entryPoints.length > 0) {
    lines.push(`- Entry points: ${analysis.entryPoints.join(', ')}`);
  }
  lines.push('');

  // Directory overview
  const dirs = new Map<string, number>();
  for (const id of graph.nodes.keys()) {
    const parts = id.split('/');
    const dir = parts.length <= 2 ? parts[0] : parts.slice(0, 2).join('/');
    dirs.set(dir, (dirs.get(dir) ?? 0) + 1);
  }
  lines.push('## Directory Overview');
  lines.push('');
  for (const [dir, count] of [...dirs.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${dir}/ (${count} files)`);
  }
  lines.push('');

  // Key Files
  lines.push('## Key Files');
  lines.push('');
  for (const mod of analysis.keyModules) {
    const node = graph.nodes.get(mod.id);
    const exports = node ? node.symbols.filter(s => s.exported).map(s => s.name).join(', ') : '';
    lines.push(`- ${mod.id} — ${mod.reason} (in: ${mod.inDegree}, out: ${mod.outDegree})${exports ? '. Exports: ' + exports : ''}`);
  }
  lines.push('');

  // Coding Conventions — skip unknown/mixed
  const c = analysis.conventions;
  const rules: string[] = [];
  if (c.exportStyle !== 'mixed') rules.push(`Use ${c.exportStyle} exports`);
  if (c.namingFunctions !== 'mixed') rules.push(`Functions: ${c.namingFunctions}`);
  if (c.namingClasses !== 'unknown' && c.namingClasses !== 'mixed') rules.push(`Classes: ${c.namingClasses}`);
  if (c.testPattern !== 'none') rules.push(`Tests: ${c.testPattern}`);

  if (rules.length > 0) {
    lines.push('## Coding Conventions');
    lines.push('');
    for (const rule of rules) {
      lines.push(`- ${rule}`);
    }
    lines.push('');
  }

  // Circular deps warning
  if (analysis.circularDeps.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const [a, b] of analysis.circularDeps) {
      lines.push(`- Circular dependency: ${a} ↔ ${b}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
