import type { Graph, AnalysisResult } from '@repo-xray/core';
import { basename } from 'node:path';

export function generateCursor(graph: Graph, analysis: AnalysisResult): string {
  const name = basename(graph.rootDir);
  const lines: string[] = [];

  lines.push('# Project Rules');
  lines.push('');
  lines.push('# Auto-generated by repo-xray — do not edit manually.');
  lines.push('');

  // Project Structure
  lines.push('## Project Structure');
  lines.push('');
  lines.push(`- **Project:** ${name}`);
  lines.push(`- **Language:** ${graph.meta.language}`);
  lines.push(`- **Modules:** ${graph.meta.totalModules}`);
  if (analysis.entryPoints.length > 0) {
    lines.push(`- **Entry points:** ${analysis.entryPoints.join(', ')}`);
  }
  lines.push('');

  // Key Files
  lines.push('## Key Files');
  lines.push('');
  for (const mod of analysis.keyModules) {
    lines.push(`- \`${mod.id}\` — ${mod.reason} (in: ${mod.inDegree}, out: ${mod.outDegree})`);
  }
  lines.push('');

  // Coding Conventions
  lines.push('## Coding Conventions');
  lines.push('');
  const c = analysis.conventions;
  lines.push(`- Export style: ${c.exportStyle}`);
  lines.push(`- Function naming: ${c.namingFunctions}`);
  lines.push(`- Class naming: ${c.namingClasses}`);
  lines.push(`- File structure: ${c.fileStructure}`);
  lines.push(`- Test pattern: ${c.testPattern}`);
  lines.push('');

  // Module Dependencies
  lines.push('## Module Dependencies');
  lines.push('');
  for (const edge of graph.edges) {
    const symbolList = edge.symbols.length > 0 ? ` (imports: ${edge.symbols.join(', ')})` : '';
    lines.push(`- \`${edge.from}\` imports \`${edge.to}\`${symbolList}`);
  }
  if (graph.edges.length === 0) {
    lines.push('No import relationships detected.');
  }
  lines.push('');

  return lines.join('\n');
}
