import { describe, it, expect } from 'vitest';
import { generateMarkdown } from './index.js';
import { buildGraph, analyze } from '@repo-xray/core';
import { resolve } from 'node:path';

const FIXTURE = resolve(import.meta.dirname, '../../../fixtures/simple-app');

describe('generateMarkdown', () => {
  it('generates CLAUDE.md with key sections', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'claude');
    expect(md).toContain('# simple-app');
    expect(md).toContain('## Project Structure');
    expect(md).toContain('## Key Modules');
    expect(md).toContain('Auto-generated by repo-xray');
  });

  it('generates CLAUDE.md with directory structure', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'claude');
    expect(md).toContain('Project Structure');
    expect(md).toContain('files');
  });

  it('does not include file-level dependency dump', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'claude');
    // Should NOT have file-level import lines like "src/handler.ts → src/utils.ts"
    expect(md).not.toContain('`src/handler.ts` →');
  });

  it('generates .cursorrules format', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'cursor');
    expect(md).toContain('Project Structure');
    expect(md).toContain('Key Files');
  });

  it('generates AGENTS.md format', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'agents');
    expect(md).toContain('## Codebase Overview');
    expect(md).toContain('## Key Modules');
  });
});
