import { describe, it, expect } from 'vitest';
import { generateMarkdown } from './index.js';
import { buildGraph, analyze } from '@repo-xray/core';
import { resolve } from 'node:path';

const FIXTURE = resolve(import.meta.dirname, '../../../fixtures/simple-app');

describe('generateMarkdown', () => {
  it('generates CLAUDE.md with architecture section', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'claude');
    expect(md).toContain('# Project: simple-app');
    expect(md).toContain('## Architecture');
    expect(md).toContain('## Key Modules');
    expect(md).toContain('## Conventions');
    expect(md).toContain('Auto-generated by repo-xray');
  });

  it('generates .cursorrules format', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'cursor');
    expect(md).toContain('Project Structure');
    expect(md).toContain('Coding Conventions');
  });

  it('generates AGENTS.md format', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'agents');
    expect(md).toContain('## Codebase Overview');
    expect(md).toContain('## Module Map');
  });

  it('includes dependency map', async () => {
    const graph = await buildGraph(FIXTURE);
    const analysis = analyze(graph);
    const md = generateMarkdown(graph, analysis, 'claude');
    expect(md).toContain('## Dependency Map');
  });
});
